version: '3.4'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
   
    ports:
      - "${POSTGRES_PORT}:5432"

    restart: always
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - back

  navi-app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      ConnectionStrings__TestDataBase: Server=postgres;Port=5432;Database=main;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Production
      JwtOptions__PrivateKey: ${JwtOptions__PrivateKey}
    volumes:
      - ${BACKEND_WWWROOT}:/app/wwwroot 
      
    ports:
      - 8080:8080

    networks:
      - back

networks:
  back:
    driver: bridge
      
volumes:
  postgres: